//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorldClient.HelloWordServiceRefference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloWordServiceRefference.HelloWorld")]
    public interface HelloWorld {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld/GetMessage", ReplyAction="http://tempuri.org/HelloWorld/GetMessageResponse")]
        string GetMessage(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld/GetMessage", ReplyAction="http://tempuri.org/HelloWorld/GetMessageResponse")]
        System.Threading.Tasks.Task<string> GetMessageAsync(string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWorldChannel : HelloWorldClient.HelloWordServiceRefference.HelloWorld, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldClient : System.ServiceModel.ClientBase<HelloWorldClient.HelloWordServiceRefference.HelloWorld>, HelloWorldClient.HelloWordServiceRefference.HelloWorld {
        
        public HelloWorldClient() {
        }
        
        public HelloWorldClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWorldClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMessage(string value) {
            return base.Channel.GetMessage(value);
        }
        
        public System.Threading.Tasks.Task<string> GetMessageAsync(string value) {
            return base.Channel.GetMessageAsync(value);
        }
    }
}
